
title: New Hugo Site
baseURL: "https://edwinthomasg.github.io/hugo-test"
markup:
  goldmark:
    renderer:
      unsafe: true
metaDataFormat: yaml

############################### TAXONOMIES ################################
taxonomies:
  chef: "chefs"

################################ PARAMS ###################################
params: 
 menu: "css/menus.css"

################################ PAGINATION ###################################
paginate: 5
paginatePath: "paginate"

################################ MENUS ###################################

menus:
 main:
  - name: "home"
    url: "/"
    weight: 1
  - name: "chefs"
    url: "/chefs"
    weight: 3
  - name: "foods"
    url: "/foods"
    weight: 2
  - name: "feeds"
    url: "/feeds"
    weight: 4
  - name: "information"
    url: "/information"
    weight: 5

