backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img
site_url: https://edwinthomasg.github.io/hugo-test/
display_url: https://edwinthomasg.github.io/hugo-test/

########################### COLLECTIONS ############################

collections:


############################## Hugo Blogs Tutorial ###############################
  - name: "tutorial"
    label: "Tutorial"
    folder: "content/hugo-blogs/tutorial"
    # creation
    slug: "created-{{title}}" 
    # inside label
    summary: "label-{{slug}}"
    # path: "sub-tutorial-one/{{slug}}"
    create: true
    edit:
     preview: true
    allow_nesting: true
    nested:
     depth: 100
     # sidebar label
     summary: "{{slug}} {{dirname}}"
     
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "date", name: "date", widget: "date" }
      