backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img
site_url: https://edwinthomasg.github.io/hugo-test/
display_url: https://edwinthomasg.github.io/hugo-test/

########################### COLLECTIONS ############################

collections:

############################## Hugo Blogs Tutorial ###############################
  - name: "tutorial"
    label: "Tutorial"
    folder: "content/hugo-blogs/tutorial"
    path: "content/hugo-blogs/tutorial/{{dirname}}"
    create: true
    edit:
     preview: true
    nested:
     depth: 100
     summary: "{{title}}-{{dirname}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "date", name: "date", widget: "date" }
      