backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img
site_url: https://edwinthomasg.github.io/hugo-test/
display_url: https://edwinthomasg.github.io/hugo-test/

########################### COLLECTIONS ############################

