backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img
site_url: https://hugo-test-site.com
display_url: https://hugo-test-site.com
show_preview_links: true
logo_url: http://localhost:1313/img/amazon.png

collections:
  - name: "custom-blog"
    label: "Blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    folder: "content/blogs"
    path: "{{year}}/{{slug}}"
    fields:
      - { label: "Blog Title", name: "title", widget: "string" }
      - { label: "body", name: "body", widget: "markdown" }
      - { label: "date", name: "date", widget: "date" }
  - name: "post"
    label: "Post"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    publish: false
    description: "small description about Post section."
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Description", name: "description", widget: "string" }
  - name: "feeds"
    label: "Feeds"
    folder: "content/feeds"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Feed Title", name: "title", widget: "string" }
      - { label: "Feed Body", name: "body", widget: "markdown" }
      - { label: "Feed Date", name: "date", widget: "date" }
      - { label: "Featured Image", name: "image", widget: "image"}
      - { label: "Privacy", name: "privacy", widget: "object", 
          fields: [
            { label: "Security", name: "privacy.security", widget: "boolean" }
          ]
        }
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        name: "home"
        label: "Home Page"
        create: true
        editor:
          preview: true
        media_folder: ""
        public_folder: ""
        fields:
          - { label: "Home Title", name: "title", widget: "string" }
          - { label: "Home Body", name: "body", widget: "markdown" }
          - { label: "Featured Image", name: "image", widget: "image"}
  - name: "news"
    label: "News Section"
    create: true
    editor:
      preview: true
    folder: "content/news"
    identifier_field: name
    delete: false
    fields:
      - { label: 'Date', name: 'date', widget: 'date' }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: posts
    label: Posts
    label_singular: "Post"
    folder: content/posts
    create: true
    allow_nesting: true
    nested:
      depth: 100
      summary: "child-{{title}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: markdown }
    meta: { path: { widget: string, label: "Path", index_file: "_index.md" } }
  - name: "nest-sub"
    label: "Nest Sub"
    create: true
    folder: "content/posts/nest-sub"
    editor: 
     preview: true
    slug: "{{year}}/{{slug}}"
    path: "{{dirname}}/{{slug}}"
    fields:
    - { label: Title, name: title, widget: string }
    - { label: Body, name: body, widget: markdown }
    - { label: Image, name: image, widget: image }
  - name: "media"
    label: "Media"
    create: true
    folder: "content/media"
    fields:
      - { label: "Media Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Creation Date", name: "date", widget: "date" }
      - { label: "Ranking", name: "weight", widget: "number"}
    sortable_fields: ["title", "date", "weight"]
    view_filters:
      - label: "By Title"
        field: title
        pattern: "Insta" # returns pages that matches the expression
      - label: "By Creation Date"
        field: date
        pattern: "2022-11"
      - label: "By Drafts"
        field: draft
        pattern: true
      - label: "By Popularity"
        field: "popular"
        pattern: true
    view_groups:
      - label: Year
        field: date
        pattern: 2021-\d{2}-\d{2}
      - label: Unpopularized
        field: popular

    