backend:
  name: git-gateway
  branch: main 
publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img
site_url: https://hugo-test-site.com
display_url: https://hugo-test-site.com
show_preview_links: false
logo_url: http://localhost:1313/img/amazon.png

collections:
  - name: 'custom-blog'
    label: 'Blog'
    folder: 'content/blogs'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    identifier_field: name
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'post'
    label: 'Post'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
     preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Description', name: 'description', widget: 'string' }
  - name: 'feeds'
    label: 'Feeds'
    folder: 'content/feeds'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' 
    editor:
     preview: true
    publish: false
    fields:
     - { label: 'Feed Title', name: 'title', widget: 'string' }
     - { label: 'Feed Body', name: 'body', widget: 'markdown'}
     - { label: 'Feed Date', name: 'date', widget: 'date'}
  - name: 'pages'
    label: 'Pages'
    files:
     - file: 'content/_index.md'
       name: 'home'
       label: 'Home Page'
       create: true
       editor:
        preview: true
       fields:
        - { label: 'Home Title', name: 'title', widget: 'string'}
        - { label: 'Home Body', name: 'body', widget: 'markdown'}
  - name: 'news'
    label: 'News Section'
    create: true
    editor:
     preview: true
    identifier_field: name
    fields:
     - { label: 'body' , name: 'body', widget: 'markdown'}

    