backend:
  name: git-gateway
  branch: main 
publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img
site_url: https://hugo-test-site.com
display_url: https://hugo-test-site.com
show_preview_links: false
logo_url: http://localhost:1313/img/amazon.png

collections:
  - name: 'custom-blog'
    label: 'Blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    folder: 'content/blogs'
    fields:
     - { label: 'Blog Title', name: 'title', widget: 'string' }
     - { label: 'body', name: 'body', widget: 'markdown' }
     - { label: 'date', name: 'date', widget: 'date' }
  - name: 'post'
    label: 'Post'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
     preview: true
    description: 'small description about Post section.'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Description', name: 'description', widget: 'string' }
  - name: 'feeds'
    label: 'Feeds'
    folder: 'content/feeds'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' 
    editor:
     preview: true
    publish: false
    fields:
     - { label: 'Feed Title', name: 'title', widget: 'string' }
     - { label: 'Feed Body', name: 'body', widget: 'markdown'}
     - { label: 'Feed Date', name: 'date', widget: 'date'}
  - name: 'pages'
    label: 'Pages'
    files:
     - file: 'content/_index.md'
       name: 'home'
       label: 'Home Page'
       create: true
       editor:
        preview: true
       fields:
        - { label: 'Home Title', name: 'title', widget: 'string'}
        - { label: 'Home Body', name: 'body', widget: 'markdown'}
  - name: 'news'
    label: 'News Section'
    create: true
    editor:
     preview: true
    folder: 'content/news'
    identifier_field: name
    fields:
     - { label: 'body' , name: 'body', widget: 'markdown'}
  - name: 'blogs'
    label: 'Blogs'
    label_singular: 'Blog'
    folder: 'content/blogs'
    create: true
    nested:
     depth: 100
     summary: 'nested: {{title}}'
    meta: 
      { 
        path: 
        { 
          widget: string, 
          label: 'Content Path',
          index_file: '_index.md'
        }
      }
    fields:
     - label: 'Sub Blog Title'
       name: 'title'
       widget: 'string'
     - label: 'Sub Blog Body'
       name: 'body'
       widget: 'markdown'

    