backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: Create {{collection}} "{{slug}}"
    update: Update {{collection}} "{{slug}}"
    delete: Delete {{collection}} "{{slug}}"
    uploadMedia: Upload "{{path}}"
    deleteMedia: Delete "{{path}}"
publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img
site_url: https://edwinthomasg.github.io/hugo-test/
display_url: https://edwinthomasg.github.io/hugo-test/

########################### COLLECTIONS ############################

collections:


############################## Hugo Blogs Tutorial ###############################
  - name: "tutorial"
    label: "Tutorial"
    folder: "content/hugo-blogs/tutorial"
    # creation
    slug: "{{fields.path}}/{{fields.title}}" 
    # path: "{{slug}}"
    # inside label
    summary: "{{slug}}"
    media_folder: ""
    public_folder: ""
    create: true
    edit:
     preview: true
    nested:
     depth: 100
    # sidebar label
     summary: "{{dirname}} {{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Date", name: "date", widget: "date" }
      - { label: "Folder Path", name: "path", widget: "string", required: false }
      - { label: "Image", name: "image", widget: "image", required: false }
      # - { label: "Location", name: "path", widget: "location", separator: "/" }
  - name: "posts"
    label: "Posts"
    create: true
    edit:
     preview: true
    folder: "content/hugo-blogs/tutorial/"
    slug: "{{fields.path}}/{{fields.title}}"
    media_folder: ""
    public_folder: ""
    nested: 
     depth: 100
     summary: "{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Folder Path", name: "path", widget: "string", required: false }
    # meta: { path: { label: Parent, widget: parent, index_file: '_index' } }
  
  - name: "artists"
    label: "Artists"
    create: true
    edit:
     preview: true
    folder: "content/information/artists"
    media_folder: ""
    public_folder: ""
    nested: 
     depth: 100
     summary: "{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image", required: false }
    meta: { path: { label: Parent, widget: parent, index_file: '_index' } }
  
  - name: "page"
    label: "Pages"
    edit:
     preview: true
    files:
      - label: "Configuration"
        name: "configuration"
        file: "config.yaml"
        fields:
          - { label: "Title", name: "title", widget: string }
          - { label: "Menus", name: "menus", widget: object, 
              fields: [{label: "Main", name: "main", widget: object, 
              fields:
                [
                {label: "Menu Name", name: "menuname", widget: string},
                {label: "Menu URL", name: "menuurl", widget: string},
                {label: "Menu Weight", name: "menuweight", widget: number},
                {label: "Menu Identifier", name: "menuidentifier", widget: string, required: false }
                ]
                }]
            }