backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img
site_url: http://localhost:1313/
display_url: http://localhost:1313/
logo_url: http://localhost:1313/img/amazon.png

collections:
  - name: "custom-blog"
    label: "Blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    folder: "content/blogs"
    path: "{{year}}/{{slug}}"
    summary: "Summary: {{dirname}} - {{title}}"
    preview_path: "blogs/{{slug}}"
    fields:
      - { label: "Blog Title", name: "title", widget: "string" }
      - { label: "body", name: "body", widget: "markdown" , minimal: true, buttons: ["bold","italic","link","heading-one","heading-three","heading-six","numbered-list"], sanitize_preview: true }
      - { label: "date", name: "date", widget: "date" }

  - name: "post"
    label: "Post"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    publish: false
    description: "small description about Post section."
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Description", name: "description", widget: "string" }

  - name: "feeds"
    label: "Feeds"
    folder: "content/feeds"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    filter: { field: "visible", value: true }
    fields:
      - { label: "Feed Title", name: "title", widget: "string" }
      - { label: "Feed Body", name: "body", widget: "markdown" }
      - { label: "Feed Date", name: "date", widget: "date" }
      - { label: "Featured Image", name: "image", widget: "image", required: false}
      - { label: "Privacy", name: "privacy", widget: "object", 
          fields: [
            { label: "Security", name: "secured", widget: "boolean", hint: "switch to set true" }
          ]
        }
      - { label: "Visible", name: "visible", widget: "hidden", default: true }
      - label: "Manual Docs"
        name: "manual_doc"
        widget: "file"
        media_folder: "/static/files"
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        name: "home"
        label: "Home Page"
        create: true
        editor:
          preview: true
        media_folder: ""
        public_folder: ""
        fields:
          - { label: "Home Title", name: "title", widget: "string" }
          - { label: "Home Body", name: "body", widget: "markdown" }
          - { label: "Featured Image", name: "image", widget: "image", required: false}
  - name: "news"
    label: "News Section"
    create: true
    editor:
      preview: true
    folder: "content/news"
    identifier_field: name
    delete: false
    fields:
      - { label: 'Date', name: 'date', widget: 'date' }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Photos"
        name: "galleryImages"
        widget: "list"
        summary: 'summary - {{fields.image}}' 
        minimize_collapsed: true
        add_to_top: true
        field: { label: Image, name: image, widget: image }
      - label: "Tags"
        name: "tags"
        widget: "list"
      - { label: "Map Location", name: "location", widget: "map" }

  - name: posts
    label: Posts
    label_singular: "Post"
    folder: content/posts
    create: true
    nested:
      depth: 100
      summary: "{{meta.path}}"
    slug: "{{year}}-{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
    meta: { path: { widget: string, label: "Path", index_file: "_index.md" } }

  - name: "nest-sub"
    label: "Nest Sub"
    create: true
    folder: "content/posts/nest-sub"
    editor: 
     preview: true
    fields:
    - { label: Title, name: title, widget: string, pattern: ["[a-zA-Z ]+", "only alphabets and - character are allowed"] }
    - { label: Body, name: body, widget: markdown }
    - { label: Image, name: image, widget: image , required: false}
    - { label: Code, name: code, widget: code, allow_language_selection: true }
    - { label: 'Color', name: 'font-color', widget: 'color', default: "blue", allowInput: true, enableAlpha: true }
    - { label: 'Tags', name: 'tags', widget: 'select', multiple: true, min: 1, max: 3, options: ["c","c++","java"], default: ["c"]}
    - label: "Media"
      name: "media"
      widget: "relation"
      collection: "media"
      search_fields: ["title","weight"]
      value_field: 'title'
      display_fields: ["title", "weight"]
  - name: "media"
    label: "Media"
    create: true
    folder: "content/media"
    fields:
      - { label: "Media Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Creation Date", name: "date", widget: "date" }
      - { label: "Ranking", name: "weight", widget: "number", value_type: "int", min: 1, max: 10, step: 2 }
      - label: "Ratings"
        name: "ratings"
        widget: "select"
        mulitple: true
        min: 1
        max: 6
        options: [
          { label: "5 star", value: 5 },
          { label: "6 star", value: 6 },
          { label: "7 star", value: 7 },
          { label: "8 star", value: 8 },
          { label: "9 star", value: 9 },
          { label: "10 star", value: 10 }
        ]
    sortable_fields: ["title", "date", "weight"]
    view_filters:
      - label: "By Title"
        field: title
        pattern: "Insta" # returns pages that matches the expression
      - label: "By Creation Date"
        field: date
        pattern: "2022-11"
      - label: "By Drafts"
        field: draft
        pattern: true
      - label: "By Popularity"
        field: "popular"
        pattern: true
    view_groups:
      - label: Year
        field: date
        pattern: 2021-\d{2}-\d{2}
      - label: Unpopularized
        field: popular

  - name: nest
    label: NestedPages
    label_singular: 'Page'
    folder: content/pages
    create: true
    nested:
      depth: 100
      summary: '{{slug}}'
    fields:
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
    meta: { path: { widget: string, label: 'Path', index_file: "_index" } }

  - name: food
    label: Food
    folder: "content/foods"
    create: true
    filter: { field: "visible", value: true }
    editor: 
     preview: true
    slug: "{{slug}}"
    summary: "{{slug}} - {{fields.weight}}"
    media_folder: "static/food/img"
    public_folder: "/food/img"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "date" }
      - { label: "Draft", name: "draft", widget: "boolean" , default: true}
      - { label: "Body", name: "body", widget: "markdown", minimal: true }
      - { label: "Weight", name: "weight", widget: "number", min: 1, max: 10 }
      - { label: "Code Section", name: "codeBlock", widget: "code", output_code_only: true, required: false }
      - { label: "Featured Image", name: "imageSource", widget: "image", choose_url: false, required: false }
      - { label: "Complement", name: "complement", widget: "list" }
      - { label: "Add Image", name: "image", widget: "list" , field : { label: "Image Source", name: "source", widget: "image" } }
      - { label: "Add Chef", name: "chefs", widget: "list", required: false }
    sortable_fields: ["title","weight"]
    view_filters:
      - { label: "ByDraft", field: "draft", pattern: true }
    view_groups:
      - { label: "Drafted", field: "draft" }
      - { label: "Chefs", field: "chefs", pattern: "suresh" }
    

    # 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 